### ISSUE TITLE
Add DataFormats folder

### ISSUE THREAD

**Issue by ktf** [Barthelemy/o2-repo-org-test#1]
Since I think we agreed we will have some sort of DataFormats folder, how about we add it to this example?

**Comment by Barthelemy** [comment]
Sure, good point. It is also a good use case for the dependencies. Let me add it.

**Comment by Barthelemy** [comment]
Done in a6e24c46a0a0275cad995861ad024528a25166cd 

I did not add the subfolders such as "include" or "src" at this stage. It might not be needed for the DataFormat that might be header only in most cases. To be seen, it is easy to change.

**Comment by ktf** [comment]
or even just a bunch of protobuf .proto files, for example. BTW, should't it be DataFormat**s**?

**Comment by Barthelemy** [comment]
yeah, in some cases it might be only that files. You are correct, spelling mistake, I'll fix it.
